### ISSUE TITLE
Cool list.

### ISSUE THREAD

**Issue by paulvanbladel** [postlight/awesome-cms#11]
What a cool list, very useful.
Do you know if a similar list exists for enterprise content management systems like alfresco, SharePoint. ...

Thx
Paul

**Comment by mutewinter** [comment]
@paulvanbladel thank you for the kind words!

I don't see anything on [Awesome list of Awesome lists](https://github.com/sindresorhus/awesome), but [Capterra's List of Content Management Systems](http://www.capterra.com/content-management-software/) seems to target the enterprise. We've use Capterra's software list to find products in the past and found it helpful.
