### ISSUE TITLE
Script urlToToml.js is missing

### ISSUE THREAD

**Issue by paescuj** [postlight/awesome-cms#114]
The script urlToToml.js mentioned in the [CONTRIBUTING.md](../blob/de5c8af1816f438a3befb2656bbd10423dd28339/CONTRIBUTING.md#convert-a-url-to-toml) is missing and should either be added or not be mentioned in the CONTRIBUTING.md file.

Thanks!

**Comment by mutewinter** [comment]
Thanks for spotting, removed in https://github.com/postlight/awesome-cms/commit/e388e297267d3c942a6d81aec63bf6d436f895d2
