### ISSUE TITLE
Differentiate between closed-sourced, commercial-with-source, and hosted

### ISSUE THREAD

**Issue by ftrain** [postlight/awesome-cms#22]
For example, Medium is hosted. Expression engine is commercial-with-source. I don't know if others are delivered as compiled—anything Java probably comes as bytecode. 

I am glad to take this assignment if no one else wants it.

**Comment by mutewinter** [comment]
Definitely an easy change to make. Just need to decide on the section names and I can implement it. Here's a thread on Twitter about Craft https://twitter.com/mathowie/status/783022249263583232.

**Comment by mjmurphy** [comment]
This could be complicated to categorise in a simple way depending on how deep you want to go. The simplest I can think of so far is to organise them into Open source, Open core, Commercial self hosted, Commercial hosted and probably one more for projects that use a dual license / freemium / shareware kind of model. For example Kirby CMS has all of its [code available on github](https://github.com/getkirby), but [requires a license](https://getkirby.com/buy) when you go live with the site. It feels kind of like a shareware model.

This is a useful guide to some open source business models that might help.
[https://github.com/nayafia/lemonade-stand](https://github.com/nayafia/lemonade-stand)
Related to that business model guide, it might be interesting (and probably controversial) to explore how some of these open source CMS projects make money e.g. some make money from their SaaS business, some have venture capital, some have commercial add ons, some have a professional services model.

A model not on that list but is worth a mention for a laugh, is the the Drug Pusher model mentioned on this post also about open source business models :
[https://handsontable.com/blog/articles/5-successful-business-models-for-web-based-open-source-projects](https://handsontable.com/blog/articles/5-successful-business-models-for-web-based-open-source-projects)

Maybe if you want to keep it simple for the layman you can use Free, Kind of free / Complicated, Not Free.

**Comment by benjamminf** [comment]
I think it'd be a good idea to rename the Closed Source section to either Commercial or Proprietary, and add another column to the table indicating these characteristics (OS, Hosted, etc.)

@mutewinter as for Craft, it always has and will be OSS – just not FOSS. It's a brilliant CMS that deserves much more attention, but it's biggest hurdle to increased marketshare is the misunderstanding that it's closed source.
